package com.luxmusic.android.ui

import androidx.compose.material3.SnackbarHostState
import androidx.compose.runtime.Composable
import com.luxmusic.android.LuxMusicUiState
import com.luxmusic.android.LuxTab

@Composable
fun LuxMusicScreen(
    uiState: LuxMusicUiState,
    snackbarHostState: SnackbarHostState,
    onSelectTab: (LuxTab) -> Unit,
    onSearchChange: (String) -> Unit,
    onImportClick: (String?) -> Unit,
    onCreatePlaylist: (String) -> Unit,
    onAddTrackToPlaylist: (String, String) -> Unit,
    onRemoveTrackFromPlaylist: (String, String) -> Unit,
    onUpdatePlaylistName: (String, String) -> Unit,
    onUpdateTrackDetails: (String, String, String) -> Unit,
    onPickTrackArtwork: (String) -> Unit,
    onPickPlaylistArtwork: (String) -> Unit,
    onPickArtistArtwork: (String) -> Unit,
    onDeleteTrack: (String) -> Unit,
    onDeletePlaylist: (String) -> Unit,
    onPlayTrack: (String) -> Unit,
    onPlayPlaylist: (String) -> Unit,
    onPlayPlaylistTrack: (String, String) -> Unit,
    onPlayArtistTrack: (String, String) -> Unit,
    onSelectQueueTrack: (String) -> Unit,
    onTogglePlayback: () -> Unit,
    onSkipPrevious: () -> Unit,
    onSkipNext: () -> Unit,
    onToggleShuffle: () -> Unit,
    onCycleRepeat: () -> Unit,
    onSeekToFraction: (Float) -> Unit,
    onDownloadUrlChange: (String) -> Unit,
    onDownloadTitleChange: (String) -> Unit,
    onDownloadLink: (String, String, String?) -> Unit,
) {
    LuxMusicRoot(
        uiState = uiState,
        snackbarHostState = snackbarHostState,
        onSelectTab = onSelectTab,
        onSearchChange = onSearchChange,
        onImportClick = onImportClick,
        onCreatePlaylist = onCreatePlaylist,
        onAddTrackToPlaylist = onAddTrackToPlaylist,
        onRemoveTrackFromPlaylist = onRemoveTrackFromPlaylist,
        onUpdatePlaylistName = onUpdatePlaylistName,
        onUpdateTrackDetails = onUpdateTrackDetails,
        onPickTrackArtwork = onPickTrackArtwork,
        onPickPlaylistArtwork = onPickPlaylistArtwork,
        onPickArtistArtwork = onPickArtistArtwork,
        onDeleteTrack = onDeleteTrack,
        onDeletePlaylist = onDeletePlaylist,
        onPlayTrack = onPlayTrack,
        onPlayPlaylist = onPlayPlaylist,
        onPlayPlaylistTrack = onPlayPlaylistTrack,
        onPlayArtistTrack = onPlayArtistTrack,
        onSelectQueueTrack = onSelectQueueTrack,
        onTogglePlayback = onTogglePlayback,
        onSkipPrevious = onSkipPrevious,
        onSkipNext = onSkipNext,
        onToggleShuffle = onToggleShuffle,
        onCycleRepeat = onCycleRepeat,
        onSeekToFraction = onSeekToFraction,
        onDownloadUrlChange = onDownloadUrlChange,
        onDownloadTitleChange = onDownloadTitleChange,
        onDownloadLink = onDownloadLink,
    )
}
